baseURL = "https://sunilgreen.github.io/"

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

# website title
title = "Sunil's ğŸ’¼"

# language code ["en", "zh-CN", "fr", "pl", ...]
languageCode = "en"
# language name ["English", "ç®€ä½“ä¸­æ–‡", "FranÃ§ais", "Polski", ...]
languageName = "English"

# Author config
[author]
  name = "Sunil Green"
  email = ""
  link = ""

# Menu config
[menu]
  [[menu.main]]
    weight = 1
    identifier = "about"
    pre = ""
    post = ""
    name = "About ğŸ™‹â€â™‚ï¸"
    url = "/about/"
    title = "About.Me"
  [[menu.main]]
    weight = 2
    identifier = "Tech"
    pre = ""
    post = ""
    name = "Tech ğŸ’»"
    url = "/tech/"
    title = "Tech"
  [[menu.main]]
    weight = 3
    identifier = "civicsanded"
    pre = ""
    post = ""
    name = "Civics & Education ğŸ›ï¸"
    url = "/civicsanded/"
    title = ""

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

